language: generic
os: linux
dist: focal
services:
  - docker

before_install:
  - docker build -t saschawissel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saschawissel/react-test npm test

after_success:
  - docker build -t saschawissel/multi-docker-test-client ./client
  - docker build -t saschawissel/multi-docker-test-nginx ./nginx
  - docker build -t saschawissel/multi-docker-test-server ./server
  - docker build -t saschawissel/multi-docker-test-worker ./worker
# Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to docker hub
  - docker push saschawissel/multi-docker-test-client
  - docker push saschawissel/multi-docker-test-nginx 
  - docker push saschawissel/multi-docker-test-server
  - docker push saschawissel/multi-docker-test-worker